# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9602f29e1366a1731bbf82adb5f8894959aff7fd209e195efb99b2b50407b64af33acd7eda602e098dcd6a216b8d3fea842866ef7f124c324a00eef18ba76e0

test:
  secret_key_base: 7f10f6edb1c1c87f79fa93eaff2e46733f4b9b26225fa687976504c06b8e2d3739e7568b0eb87e20c568cf1b90b0da9cea89a81b9f7b2aac0932282d62ced20e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
